2022-04-25 16:44:02.713 | INFO     | __main__:server:72 - 启动服务：192.168.23.1:56112
2022-04-25 16:44:02.715 | INFO     | __main__:server:75 - 服务注册开始
2022-04-25 16:44:02.729 | INFO     | __main__:server:82 - 服务注册成功
2022-04-25 16:53:28.355 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (2956), thread 'ThreadPoolExecutor-0_8' (7240):
Traceback (most recent call last):

  File "D:\pycharm\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 795, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001BDA42A1EC8>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001BDA42A1EC8>
          │    └ <bound method Thread._bootstrap of <Thread(ThreadPoolExecutor-0_8, started daemon 7240)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001BDA42A1EC8>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001BD85E9CD38>
    └ <Thread(ThreadPoolExecutor-0_8, started daemon 7240)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001BD85E9CAF8>
    └ <Thread(ThreadPoolExecutor-0_8, started daemon 7240)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_8, started daemon 7240)>
    │    │        │    └ (<weakref at 0x000001BDA42A6A48; to 'ThreadPoolExecutor' at 0x000001BDA3FDCB88>, <_queue.SimpleQueue object at 0x000001BDA3FF...
    │    │        └ <Thread(ThreadPoolExecutor-0_8, started daemon 7240)>
    │    └ <function _worker at 0x000001BDA40061F8>
    └ <Thread(ThreadPoolExecutor-0_8, started daemon 7240)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001BDA40063A8>
    └ <concurrent.futures.thread._WorkItem object at 0x000001BDA42BE288>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001BDA42BE288>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001BDA42BF318>, <grpc._server._RPCState object at 0x000001BDA42BE1C8>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001BDA42BE288>
             │    └ <function _unary_response_in_pool at 0x000001BDA40359D8>
             └ <concurrent.futures.thread._WorkItem object at 0x000001BDA42BE288>

  File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 561, in _unary_response_in_pool
    argument, request_deserializer)
    │         └ <built-in method FromString of GeneratedProtocolMessageType object at 0x000001BDA1363188>
    └ isNew: true

> File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001BDA42BE208>
                           │        └ isNew: true
                           │          
                           └ <bound method GoodsServicer.GoodsList of <goods_srv.handler.goods.GoodsServicer object at 0x000001BDA3FFF088>>

  File "D:\PythonProjects\shop\goods_srv\handler\goods.py", line 90, in GoodsList
    rsp.data.append(self.convert_model_to_message(good))
    │   │           │    │                        └ <Goods: 421>
    │   │           │    └ <function GoodsServicer.convert_model_to_message at 0x000001BDA388FD38>
    │   │           └ <goods_srv.handler.goods.GoodsServicer object at 0x000001BDA3FFF088>
    │   └ <field property 'GoodsListResponse.data'>
    └ total: 2

  File "D:\PythonProjects\shop\goods_srv\handler\goods.py", line 33, in convert_model_to_message
    info_rsp.logo = goods.brand.logo
    │               │     └ <peewee.ForeignKeyAccessor object at 0x000001BDA3B85C88>
    │               └ <Goods: 421>
    └ id: 421
      categoryId: 164600
      name: "\347\203\237\345\217\260\347\272\242\345\257\214\345\243\253\350\213\271\346\236\23412\344\...

AttributeError: 'GoodsInfoResponse' object has no attribute 'logo'
