2022-04-25 17:01:43.427 | INFO     | __main__:server:72 - 启动服务：192.168.23.1:56937
2022-04-25 17:01:43.429 | INFO     | __main__:server:75 - 服务注册开始
2022-04-25 17:01:43.444 | INFO     | __main__:server:82 - 服务注册成功
2022-04-25 17:06:25.606 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (18812), thread 'ThreadPoolExecutor-0_2' (3096):
Traceback (most recent call last):

  File "D:\pycharm\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 795, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001A03157D808>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001A03157D808>
          │    └ <bound method Thread._bootstrap of <Thread(ThreadPoolExecutor-0_2, started daemon 3096)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x000001A03157D808>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001A0131ACD38>
    └ <Thread(ThreadPoolExecutor-0_2, started daemon 3096)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001A0131ACAF8>
    └ <Thread(ThreadPoolExecutor-0_2, started daemon 3096)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_2, started daemon 3096)>
    │    │        │    └ (<weakref at 0x000001A031591958; to 'ThreadPoolExecutor' at 0x000001A0312E8F08>, <_queue.SimpleQueue object at 0x000001A0312F...
    │    │        └ <Thread(ThreadPoolExecutor-0_2, started daemon 3096)>
    │    └ <function _worker at 0x000001A031309168>
    └ <Thread(ThreadPoolExecutor-0_2, started daemon 3096)>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000001A031309318>
    └ <concurrent.futures.thread._WorkItem object at 0x000001A0316A9F48>

  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000001A0316A9F48>
             │    │   │    └ [<grpc._cython.cygrpc.RequestCallEvent object at 0x000001A0316AD318>, <grpc._server._RPCState object at 0x000001A0316A9E48>, ...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000001A0316A9F48>
             │    └ <function _unary_response_in_pool at 0x000001A0313368B8>
             └ <concurrent.futures.thread._WorkItem object at 0x000001A0316A9F48>

  File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 561, in _unary_response_in_pool
    argument, request_deserializer)
    │         └ <built-in method FromString of GeneratedProtocolMessageType object at 0x000001A02E370938>
    └ isNew: true

> File "D:\virtual-environment\py3.7\lib\site-packages\grpc\_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x000001A0316B0048>
                           │        └ isNew: true
                           │          
                           └ <bound method GoodsServicer.GoodsList of <goods_srv.handler.goods.GoodsServicer object at 0x000001A03130A608>>

  File "D:\PythonProjects\shop\goods_srv\handler\goods.py", line 90, in GoodsList
    rsp.data.append(self.convert_model_to_message(good))
    │   │           │    │                        └ <Goods: 421>
    │   │           │    └ <function GoodsServicer.convert_model_to_message at 0x000001A030B8FD38>
    │   │           └ <goods_srv.handler.goods.GoodsServicer object at 0x000001A03130A608>
    │   └ <field property 'GoodsListResponse.data'>
    └ total: 2

  File "D:\PythonProjects\shop\goods_srv\handler\goods.py", line 33, in convert_model_to_message
    info_rsp.logo = goods.brand.logo
    │               │     └ <peewee.ForeignKeyAccessor object at 0x000001A030E86E08>
    │               └ <Goods: 421>
    └ id: 421
      categoryId: 164600
      name: "\347\203\237\345\217\260\347\272\242\345\257\214\345\243\253\350\213\271\346\236\23412\344\...

AttributeError: 'GoodsInfoResponse' object has no attribute 'logo'
